### ISSUE TITLE
Ignores parts already in bags,

### ISSUE THREAD

**Issue by ImSundee** [taxidriveer/Hemlock#1]
As rogues we get alot of the required ingredients from pick pocketing, could the add on use whats in your bags before purchasing more - and also when purchasing take into count what you already have.

Thanks and keep up this awesome addon!

**Comment by taxidriveer** [comment]
Hi,
Thanks for the kind words, this feature should already be implemented.
Could you let me know what poison and rank aren't working as intended?

**Comment by taxidriveer** [comment]
Closing, already implented
